# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

clone_depth: 5

cache:
- downloads/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
- downloads/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z

# https://www.appveyor.com/docs/windows-images-software/
image: Visual Studio 2019

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  ENABLE_COVERAGE: no
  matrix:
  - MINGW_TARGET: mingw64
  - MINGW_TARGET: mingw32

install:
- set Path=C:\Python36-x64;%Path%
# CMake refuses to generate MinGW Makefiles if sh.exe is in the Path
- ps: Get-Command sh.exe -All | Remove-Item

build_script:
- powershell -NoProfile -ExecutionPolicy Bypass -file build.ps1 -buildRoot %CD%\build -target %MINGW_TARGET%

artifacts:
- path: build\mingw??\drmingw-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: E46gT6yNIKl9L5tmcJdNY6NJ+KXmaNV7U19ZpNjz2R8U2dRUwBceMKqCHE5cs3JA
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
