name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [mingw64, mingw32]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Cache Downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: downloads/*.7z
        key: ${{ runner.os }}-${{ matrix.target }}-mingw-10.2.0-dbghelp-10.0.18362.1
    - run: Get-Host | Select-Object Version
    #- run: python -m pip install gcovr codecov
    - name: Build
      run: .\ci\build.ps1 -target ${{ matrix.target }} -coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: drmingw-${{ matrix.target }}
        path: build/mingw??/drmingw-*.7z
        if-no-files-found: error
