name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [mingw64, mingw32]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Cache Downloads
      id: cache-downloads
      uses: actions/cache@v2
      with:
        path: downloads/*.7z
        key: ${{ runner.os }}-${{ matrix.target }}-mingw-8.1.0-v6
    - run: Get-Host | Select-Object Version
    - run: python -m pip install gcovr codecov
    - name: Build
      run: .\build.ps1 -target ${{ matrix.target }} -coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
